In [1]:
#1. Import the NUMPY package under the name np.
import numpy as np
import pandas as pd
from pprint import pprint


In [2]:
#2. Print the NUMPY version and the configuration.
print(np.version.version)
print(np.__config__)

1.16.2
<module 'numpy.__config__' from 'C:\\Users\\Paul\\Anaconda3\\lib\\site-packages\\numpy\\__config__.py'>


In [3]:
#3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
# Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

a = np.random.rand(2,3,5)
aa = np.random.random((2,3,5))
aaa = np.random.random_sample((2,3,5))

In [4]:
# Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

# Méthode 1 : Distribution uniforme entre 0 et 1
a_1 = np.random.rand(2,3,5)
print("dim 1 :",len(a_1))
print("dim 2 :",len(a_1[0]))
print("dim 3 :",len(a_1[0][0]))
print("First element :", ((a_1[0][0][0])))
# On affiche le tableau
pprint((a_1))


# Méthode 2 : On ne génère que des entiers (distributoion uniforme)
# On génère des entiers entre 0 et 5 (exclus), contenus dans une matrice de taille
# 2 * 3 * 5
a_2 = np.random.randint(5, size=(2,3,5))
print("dim 1 :",len(a_2))
print("dim 2 :",len(a_2[0]))
print("dim 3 :",len(a_2[0][0]))
print("First element :", ((a_2[0][0][0])))
# On affiche le tableau
pprint((a_2))


# Méthode 3 : Distribution uniforme entre 0 et 1
a_3 = np.random.random_sample(size=(2, 3, 5))
print("dim 1 :",len(a_3))
print("dim 2 :",len(a_3[0]))
print("dim 3 :",len(a_3[0][0]))
print("First element :", ((a_3[0][0][0])))
# On affiche le tableau
pprint(a_3)

dim 1 : 2
dim 2 : 3
dim 3 : 5
First element : 0.5115798026343797
array([[[0.5115798 , 0.13121158, 0.10855777, 0.46581629, 0.62329065],
        [0.33892771, 0.61203983, 0.14275697, 0.70757377, 0.45202328],
        [0.33147804, 0.95042679, 0.40122156, 0.97604713, 0.53690917]],

       [[0.28884592, 0.95794605, 0.8387822 , 0.79927861, 0.98708892],
        [0.22177947, 0.7960151 , 0.93101034, 0.05086602, 0.49037903],
        [0.20664418, 0.63699047, 0.25709667, 0.21666443, 0.99256374]]])
dim 1 : 2
dim 2 : 3
dim 3 : 5
First element : 4
array([[[4, 1, 0, 4, 0],
        [0, 3, 4, 2, 4],
        [0, 1, 4, 1, 1]],

       [[1, 3, 2, 1, 3],
        [1, 3, 3, 4, 4],
        [2, 2, 3, 0, 2]]])
dim 1 : 2
dim 2 : 3
dim 3 : 5
First element : 0.9661861769692041
array([[[0.96618618, 0.74239945, 0.09888874, 0.52169778, 0.80091919],
        [0.84591692, 0.44424619, 0.94926405, 0.0131731 , 0.60893473],
        [0.39452078, 0.37842593, 0.86395673, 0.42697368, 0.87945528]],

       [[0.06069599, 0.84167874,

In [5]:
#4. Print a.

print("first option", a)
print("second option", aa)
print("third option", aaa)

first option [[[0.31593869 0.18005401 0.84275044 0.47588753 0.45950711]
  [0.97013272 0.72839242 0.08933816 0.22593354 0.37012492]
  [0.03027076 0.33091787 0.74459611 0.83093714 0.85890721]]

 [[0.06473826 0.24978807 0.55377097 0.8836141  0.19400732]
  [0.66475888 0.43855217 0.10581425 0.08086288 0.34417597]
  [0.16587535 0.78443946 0.03512008 0.45173164 0.11644654]]]
second option [[[0.35158243 0.08641451 0.24867629 0.34909161 0.75865535]
  [0.76731957 0.23004065 0.26075339 0.09519276 0.6180807 ]
  [0.05811317 0.39872551 0.49961645 0.44731988 0.34893873]]

 [[0.15983169 0.70284102 0.91921759 0.86759963 0.28164124]
  [0.27903566 0.56765574 0.81438131 0.45047217 0.56177497]
  [0.58947476 0.09984895 0.52690839 0.58762443 0.88564354]]]
third option [[[0.51197096 0.21073374 0.86681293 0.58571618 0.33167423]
  [0.42094186 0.8782299  0.5895975  0.71177487 0.09487034]
  [0.54651159 0.25362647 0.12881923 0.73185966 0.1846416 ]]

 [[0.53140195 0.23609798 0.76295852 0.103654   0.42802092]
  [0.5

In [10]:
#5. Create a 5x2x3 3-dimensional array with all values equaling 1.
#Assign the array to variable "b"
#(b - a) * random_sample() + a

b = np.ones((5, 2, 3))
#b = np.random.random_sample((5,2,3))

In [11]:
#6. Print b.

print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


In [12]:
#7. Do a and b have the same size? How do you prove that in Python code?
#print("a lenghts", len(a))
#print("b lengths", len(b))
print("shape of a : {}".format(a.shape))
print("shape of b : {}".format(b.shape))
print(len(a)==len(b))
print("a shapes", a.shape)
print("b shapes", b.shape)

shape of a : (2, 3, 5)
shape of b : (5, 2, 3)
False
a shapes (2, 3, 5)
b shapes (5, 2, 3)


In [9]:
#8. Are you able to add a and b? Why or why not?
ab = a + b
print(ab) #not able to add a and b as operands could not be broadcast together with different shapes here (2,3,5) and (5,2,3) 

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

In [13]:
#9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".
c = b.reshape(2, 3, 5)

In [15]:
#9. correction from Selim
print("shape of b : {}".format(b.shape))
# b has format (5, 2, 3) and a has format (2, 3, 5)
# so we need to swap dim 0 and dim 1 in b, then we get (2, 5, 3)
c = np.swapaxes(b, 0, 1).copy()
print("With swap 1st step : shape of c : {}".format(c.shape))
# then we need to swap dim 1 and dim 2 in the c newly obtained and we get (2, 3, 5)
c = np.swapaxes(c, 1, 2)
print("With swap 2nd step : shape of c : {}".format(c.shape))
# Plus efficace : en 1 appel d'une fonction (merci Lauma)
c = b.transpose([1,2,0])
print("With transpose in 1 step : shape of c : {}".format(c.shape))

shape of b : (5, 2, 3)
With swap 1st step : shape of c : (2, 5, 3)
With swap 2nd step : shape of c : (2, 3, 5)
With transpose in 1 step : shape of c : (2, 3, 5)


In [16]:
#10. Try to add a and c. Now it should work. Assign the sum to varialbe "d". But why does it work now?
d = a + c # a and c have the same array structure (2,3,5)

In [17]:
#11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.
print("a=",a)
print("d=",d)

a= [[[0.31593869 0.18005401 0.84275044 0.47588753 0.45950711]
  [0.97013272 0.72839242 0.08933816 0.22593354 0.37012492]
  [0.03027076 0.33091787 0.74459611 0.83093714 0.85890721]]

 [[0.06473826 0.24978807 0.55377097 0.8836141  0.19400732]
  [0.66475888 0.43855217 0.10581425 0.08086288 0.34417597]
  [0.16587535 0.78443946 0.03512008 0.45173164 0.11644654]]]
d= [[[1.31593869 1.18005401 1.84275044 1.47588753 1.45950711]
  [1.97013272 1.72839242 1.08933816 1.22593354 1.37012492]
  [1.03027076 1.33091787 1.74459611 1.83093714 1.85890721]]

 [[1.06473826 1.24978807 1.55377097 1.8836141  1.19400732]
  [1.66475888 1.43855217 1.10581425 1.08086288 1.34417597]
  [1.16587535 1.78443946 1.03512008 1.45173164 1.11644654]]]


In [18]:
#12. Multiply a and c. Assign the result to e.
e = a*c
print(e)

[[[0.31593869 0.18005401 0.84275044 0.47588753 0.45950711]
  [0.97013272 0.72839242 0.08933816 0.22593354 0.37012492]
  [0.03027076 0.33091787 0.74459611 0.83093714 0.85890721]]

 [[0.06473826 0.24978807 0.55377097 0.8836141  0.19400732]
  [0.66475888 0.43855217 0.10581425 0.08086288 0.34417597]
  [0.16587535 0.78443946 0.03512008 0.45173164 0.11644654]]]


In [19]:
print("shape of e : {}".format(e.shape))

shape of e : (2, 3, 5)


In [20]:
#13. Does e equal to a? Why or why not?
print(a==e) 

# Classical multiplication (with *) applied to 2 numpy darrays return 
# a vector of same shape than both a and c
# this is pairwise multiplication meaning : e[i][j][k] = a[i][j][k] * c[i][j][k]
# e = a because all elements of b are equal to 1

[[[ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]]

 [[ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]]]


In [21]:
#14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)
print('In d, the max value is', d_max,', the min value is', d_min, 'the mean value is', d_mean)

print("max : {0:.2f}, min : {1:.2f}, mean : {2:.2f}".format(d_max, d_min, d_mean))
# Meaning : 0th value with 2 decimals, then 1st then 2nd  
# (from the 0th, 1st and 2nd value specified as an argument)

In d, the max value is 1.9701327192922173 , the min value is 1.0302707587295634 the mean value is 1.4195794848659509
max : 1.97, min : 1.03, mean : 1.42


In [22]:
#15. Now we want to label the values in d. 
#First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.
f = np.empty([2,3,5])

In [23]:
#16. Populate the values in f. 
print(f)

[[[0.31593869 0.18005401 0.84275044 0.47588753 0.45950711]
  [0.97013272 0.72839242 0.08933816 0.22593354 0.37012492]
  [0.03027076 0.33091787 0.74459611 0.83093714 0.85890721]]

 [[0.06473826 0.24978807 0.55377097 0.8836141  0.19400732]
  [0.66475888 0.43855217 0.10581425 0.08086288 0.34417597]
  [0.16587535 0.78443946 0.03512008 0.45173164 0.11644654]]]


In [27]:
"""
16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.

"""

"\n16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.\nIf a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.\nIf a value equals to d_mean, assign 50 to the corresponding value in f.\nAssign 0 to the corresponding value(s) in f for d_min in d.\nAssign 100 to the corresponding value(s) in f for d_max in d.\nIn the end, f should have only the following values: 0, 25, 50, 75, and 100.\nNote: you don't have to use Numpy in this question.\n\n"

In [24]:
print("We first iterate over the first dimension which is equal to {}".format(len(d)))
print("We first iterate over the second dimension which is equal to {}".format(len(d[0])))
print("We first iterate over the second dimension which is equal to {}".format(len(d[0][0])))

# First dim = 2
for i in range(len(f)):
    # Second dim = 3
    for j in range(len(f[0])):
        # Third dim = 5
        for k in range(len(f[0][0])):
            if  d_min < d[i][j][k] < d_mean:
                f[i][j][k] = 25
            elif  d_mean < d[i][j][k] < d_max :
                f[i][j][k] = 75
            else:
                f[i][j][k] = 50
print(f)

We first iterate over the first dimension which is equal to 2
We first iterate over the second dimension which is equal to 3
We first iterate over the second dimension which is equal to 5
[[[25. 25. 75. 75. 75.]
  [50. 75. 25. 25. 25.]
  [50. 25. 75. 75. 75.]]

 [[25. 25. 75. 75. 25.]
  [75. 75. 25. 25. 25.]
  [25. 75. 25. 75. 25.]]]


In [28]:
# Beaucoup plus élégant : avec la fonction vectorize : 
# transforme une fonction qui prend en entrée un nombre, 
# en une fonction qui prend en entrée un vecteur et applique cette fonction a tous les éléments

# d will be an element of d
def f_fun(d_min, d_max, d_mean, d):
    if  d_min < d < d_mean:
        f = 25
    elif  d_mean < d < d_max :
        f = 75
    elif d == d_mean :
        f= 50
    elif d == d_min :
        f= 0
    elif d == d_max :
        f = 100
    return f

# python-function as ufunc
import numpy as np
vf= np.vectorize(lambda x :f_fun(d_min=d_min, d_max=d_max, d_mean=d_mean, d=x))
## On récupère bien le même output
f == vf(d)
print(vf(d))

[[[ 25  25  75  75  75]
  [100  75  25  25  25]
  [  0  25  75  75  75]]

 [[ 25  25  75  75  25]
  [ 75  75  25  25  25]
  [ 25  75  25  75  25]]]


In [29]:
#here is the numpy version
f[np.where(d>d_min) and (d<d_mean)] = 25
f[np.where(d>d_mean) and (d<d_max)] = 75
f[np.where(d == d_mean)] = 50
f[np.where(d_min == d)] = 0
f[np.where(d_max == d)] = 100

In [30]:
#In the end, f should have only the following values: 0, 25, 50, 75, and 100.
#Note: you don't have to use Numpy in this question.
print(f)

[[[ 75.  75.  75.  75.  75.]
  [100.  75.  75.  75.  75.]
  [  0.  75.  75.  75.  75.]]

 [[ 75.  75.  75.  75.  75.]
  [ 75.  75.  75.  75.  75.]
  [ 75.  75.  75.  75.  75.]]]


In [ ]:
"""
#17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])
"""

In [ ]:
d = np.array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)

print("max : {0:.2f}, min : {1:.2f}, mean : {2:.2f}".format(d_max, d_min, d_mean))
# Meaning : 0th value with 2 decimals, then 1st then 2nd  
# (from the 0th, 1st and 2nd value specified as an argument)

In [32]:
## Avec une boucle

print("We first iterate over the first dimension which is equal to {}".format(len(d)))
print("We first iterate over the second dimension which is equal to {}".format(len(d[0])))
print("We first iterate over the second dimension which is equal to {}".format(len(d[0][0])))

# First dim = 2
for i in range(len(d)):
    # Second dim = 3
    for j in range(len(d[0])):
        # Third dim = 5
        for k in range(len(d[0][0])):
            if  d_min < d[i][j][k] < d_mean:
                f[i][j][k] = 25
            elif  d_mean < d[i][j][k] < d_max :
                f[i][j][k] = 75
            elif d[i][j][k] == d_mean :
                f[i][j][k] = 50
            elif d[i][j][k] == d_min :
                f[i][j][k] = 0
            elif d[i][j][k] == d_max :
                f[i][j][k] = 100
# Beaucoup plus élégant : avec la fonction vectorize : 
# transforme une fonction qui prend en entrée un nombre, 
# en une fonction qui prend en entrée un vecteur et applique cette fonction a tous les éléments

# d will be an element of d
def f_fun(d_min, d_max, d_mean, d):
    if  d_min < d < d_mean:
        f = 25
    elif  d_mean < d < d_max :
        f = 75
    elif d == d_mean :
        f= 50
    elif d == d_min :
        f= 0
    elif d == d_max :
        f = 100
    return f

# python-function as ufunc
import numpy as np
vf= np.vectorize(lambda x :f_fun(d_min=d_min, d_max=d_max, d_mean=d_mean, d=x))
## On récupère bien le même output
f == vf(d)
print(vf(d))

We first iterate over the first dimension which is equal to 2
We first iterate over the second dimension which is equal to 3
We first iterate over the second dimension which is equal to 5
[[[ 25  25  75  75  75]
  [100  75  25  25  25]
  [  0  25  75  75  75]]

 [[ 25  25  75  75  25]
  [ 75  75  25  25  25]
  [ 25  75  25  75  25]]]


In [ ]:
#18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
"""
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.
"""

In [31]:
# Beaucoup plus élégant : avec la fonction vectorize : 
# transforme une fonction qui prend en entrée un nombre, 
# en une fonction qui prend en entrée un vecteur et applique cette fonction a tous les éléments

# d will be an element of d
def f_fun(d_min, d_max, d_mean, d):
    if  d_min < d < d_mean:
        f = "B"
    elif  d_mean < d < d_max :
        f = "D"
    elif d == d_mean :
        f= "C"
    elif d == d_min :
        f= "A"
    elif d == d_max :
        f = "E"
    return f

# python-function as ufunc
import numpy as np
vf= np.vectorize(lambda x :f_fun(d_min=d_min, d_max=d_max, d_mean=d_mean, d=x))
print(vf(d))

[[['B' 'B' 'D' 'D' 'D']
  ['E' 'D' 'B' 'B' 'B']
  ['A' 'B' 'D' 'D' 'D']]

 [['B' 'B' 'D' 'D' 'B']
  ['D' 'D' 'B' 'B' 'B']
  ['B' 'D' 'B' 'D' 'B']]]
